### ISSUE TITLE
Error Documentation

### ISSUE THREAD

**Issue by hippyfox** [datawookie/binance#11]
The link to the Documentation Leads to a 404:Error

Also, is there any chance to get a pdf document on this library (like the rgdax one)?

**Comment by datawookie** [comment]
Hi @hippyfox, I'm Andrew (or datawookie). Pleased to meet you.

**Comment by datawookie** [comment]
Hi @hippyfox,

> The link to the Documentation Leads to a 404:Error

Thanks for letting me know. Fixing that now.

> Also, is there any chance to get a pdf document on this library (like the rgdax one)?

You mean like [this](https://cran.r-project.org/web/packages/rgdax/rgdax.pdf)? If so, then yes I can build a PDF version of the documentation. But that feels a little premature to me, given that I still have a lot of work to do to get basic coverage on the API. In the short term you can get an index to the documentation with `library(help = "binance")`.

Are there any bits of functionality that you are specifically interested in?

Regards, Andrew.

**Comment by datawookie** [comment]
Okay, https://datawookie.github.io/binance/index.html is working now. I think that https://datawookie.github.io/binance/ is currently cached. But when that expires it should also work.
