### ISSUE TITLE
Adapt it to Binance.us

### ISSUE THREAD

**Issue by astraetech** [datawookie/binance#12]
Hi,

A great package!  I'm working on adapting this for binance.us but i keep getting errors like this one.

`
> wallet_daily_snapshot(type="SPOT",start_time = "2021-10-02", limit = 30)
Error: Must extract column with a single valid subscript.
x Subscript `var` has the wrong type `function`.
i It must be numeric or character.
Run `rlang::last_error()` to see where the error occurred `

The API keys work well when I check them with python-binance. Any way of introducing binance.US support?

**Comment by datawookie** [comment]
Hi @astraetech,

Without knowing what adaptions you have made or the context of your code fragment, it's hard to help. Please provide more information and I'll take a look.

Thanks, Andrew.

**Comment by astraetech** [comment]
Actually the only thing i did is in this commit: https://github.com/astraetech/binance/commit/51f5f000b465b9784b6d307a8a91e7bd36ddd0b7#diff-c9b8b5f14cf78cb40672b44fe6e9743d1fc618477a31074dab8565954dd8229f Not sure how to reference commits on Github.

BAsically 

`cache$BASE_URL <- "https://api.binance.us"`
instead of 
`cache$BASE_URL <- "https://api.binance.com"`

**Comment by datawookie** [comment]
Hi @astraetech,

Okay, you don't need to change the code to get a different base URL. Just do this:

**Comment by datawookie** [comment]
Hi @astraetech,

Based on the output which you get (below) I'm guessing that you don't have any accounts on this platform. The API query was successful (`code` is 200) but the `snapshotVos` element is empty. Do you have accounts with transactions on Binance US?

Regards, Andrew.

```
$code
[1] 200

$msg
[1] ""

$snapshotVos
list()
```

**Comment by astraetech** [comment]
Hi @datawookie,

I have an acct in Binance.US. As i mentioned in the first post I have API keys from binance.us that work in python-binance and show me my acct withdrawals and trades for instance. I have set this line in python-binance though:
`client = Client(api_key, api_secret, tld='us')`

**Comment by datawookie** [comment]
No problem, @astraetech, let me dig deeper.

What function are you using in the Python package to access the daily snapshots?

**Comment by astraetech** [comment]
Hi @datawookie,

Thanks for looking into this! I'm using the sample code from the python-binance:

```
api_key = "XXXX"
api_secret = "XXXX"

from binance import Client, ThreadedWebsocketManager, ThreadedDepthCacheManager
client = Client(api_key, api_secret, tld='us')

trades = client.get_my_trades(symbol='BTCUSD')


print(trades)
[{'symbol': 'BTCUSD', ..... and so on prints all the trades on the account for that coin }]

info = client.get_account_snapshot(type='SPOT')

print(info)
{'code': 200, 'msg': '', 'snapshotVos': []}

```

It seems that the snapshot gives the same result in python-binance for binance.us  - an empty list.

**Comment by datawookie** [comment]
Aha! Okay, so the result that you are getting from `{binance}` is consistent with what you are getting with the Python package. Good!

What about the trades? Do those tie up across the R and Python packages?

**Comment by astraetech** [comment]
Trades seem to tie up but i could only test two pairs, as my python skills not enough to get trades for the whole portfolio.

Your package seems to work for Binance Global accounts well and it seems that accountSnapshot endpoint is enabled for the Global but not for the US? I went through the Binance US API documentation several times but couldn't find it. Maybe it's undocumented? It's extremely useful.

I tried using "/api/v3/account" endpoint for the US and it returns a current account snapshot with a slightly different JSON payload structure.
```
str(binance_us_acct)
List of 11
 $ makerCommission : int 10
 $ takerCommission : int 10
 $ buyerCommission : int 0
 $ sellerCommission: int 0
 $ canTrade        : logi TRUE
 $ canWithdraw     : logi TRUE
 $ canDeposit      : logi TRUE
 $ updateTime      : num 1638092142562
 $ accountType     : chr "SPOT"
 $ balances        :List of 65
  ..$ :List of 3
  .. ..$ asset : chr "BTC"
  .. ..$ free  : chr "0.00637400"
  .. ..$ locked: chr "0.00000000"
  ..$ :List of 3
  .. ..$ asset : chr "ETH"
  .. ..$ free  : chr "0.08258000"
  .. ..$ locked: chr "0.00000000"
```

**Comment by datawookie** [comment]
@astraetech comparing this with the raw result from www.binance.com:

```
List of 11
 $ makerCommission : int 10
 $ takerCommission : int 10
 $ buyerCommission : int 0
 $ sellerCommission: int 0
 $ canTrade        : logi TRUE
 $ canWithdraw     : logi TRUE
 $ canDeposit      : logi TRUE
 $ updateTime      : num 1.64e+12
 $ accountType     : chr "SPOT"
 $ balances        :List of 472
  ..$ :List of 3
  .. ..$ asset : chr "BTC"
  .. ..$ free  : chr "0.00000000"
  .. ..$ locked: chr "0.00000000"
  ..$ :List of 3
  .. ..$ asset : chr "LTC"
  .. ..$ free  : chr "0.00000000"
  .. ..$ locked: chr "0.00000000"
```
