### ISSUE TITLE
[BUG]: spot_new_order, test and fills TRUE = column not found.

### ISSUE THREAD

**Issue by nilsps** [datawookie/binance#14]
### Description of the bug

When running the code at spot_new_order, test and fill set to true. The script cannot find a column. Full traceback can be found below. 

Traceback found at: 
[bug_binance.txt](https://github.com/datawookie/binance/files/9141788/bug_binance.txt)

### Steps To Reproduce

Spot new order, crashes with these parameters. 

spot_new_order(
  order_type = "LIMIT",
  symbol = "LTCUSDT",
  side = "SELL",
  quantity = 1,
  price = 67,
  time_in_force = "GTC",
  test = TRUE,
  fills = TRUE
)

To remove the bug, remove test and fills, as example below: 

spot_new_order(
  order_type = "LIMIT",
  symbol = "LTCUSDT",
  side = "SELL",
  quantity = 1,
  price = 67,
  time_in_force = "GTC"
)

### Additional Information

binance 0.0.5

**Comment by datawookie** [comment]
Hi @nilsps,

I have pushed a fix to GitHub. Please install again using `remotes::install_github("datawookie/binance")`.

Creating a new order:

```
 spot_new_order(
+   order_type = "LIMIT",
+   symbol = "LTCUSDT",
+   side = "SELL",
+   quantity = 1,
+   price = 67,
+   time_in_force = "GTC"
+ )
# A tibble: 1 × 11
  symbol  order_id transact_time       price orig_qty exec_qty status time_in_force type  side  fills           
  <chr>      <int> <dttm>              <dbl>    <dbl>    <dbl> <chr>  <chr>         <chr> <chr> <list>          
1 LTCUSDT   737199 2022-07-19 14:41:26    67        1        0 NEW    GTC           LIMIT SELL  <tibble [0 × 0]>
```

Testing (successful):

```
> spot_new_order(
+   order_type = "LIMIT",
+   symbol = "LTCUSDT",
+   side = "SELL",
+   quantity = 1,
+   price = 67,
+   time_in_force = "GTC",
+   test = TRUE
+ )
[1] TRUE
```

Testing (failure):

```
> spot_new_order(
+   order_type = "LIMIT",
+   symbol = "BOGUS",
+   side = "SELL",
+   quantity = 1,
+   price = 67,
+   time_in_force = "GTC",
+   test = TRUE
+ )
[1] FALSE
```
