### ISSUE TITLE
Interface for posting ads in p2p

### ISSUE THREAD

**Issue by riven314** [datawookie/binance#16]
Great work!
I saw from ur blogpost that u implemented interfaces for fetching ads in p2p markets
Does the package also offer interfaces for creating ads, and clicking the payment confirmation button ?

**Comment by datawookie** [comment]
Hi @riven314, thanks. No, I'm afraid not. For the moment it only supports the functionality to search existing P2P ads. I'm not even sure if it's possible to create ads via the API. If it is possible and there's demand for this feature then I could certainly investigate implementing it into the `{binance}` package. Thanks, Andrew.
