### ISSUE TITLE
Funding balance

### ISSUE THREAD

**Issue by laresbernardo** [datawookie/binance#7]
Is there a way to fetch our "Funding" (tab) balance? Preferably with daily break down. 
Opening new ticket to follow up on [this ticket](https://github.com/datawookie/binance/issues/5#issuecomment-957039693).

**Comment by datawookie** [comment]
@laresbernardo have you identified an endpoint in the API which would provide this information?

**Comment by laresbernardo** [comment]
Sharing a screenshot of the FUNDING wallet. I still haven't found a way to get those transactions/balance. The transactions can be found in the Payment History option within Funding, also known as Binance Pay.
![IMG_0164](https://user-images.githubusercontent.com/25909073/152458092-eecf89ec-78dc-461f-94af-26322fc6d779.jpeg)

**Comment by datawookie** [comment]
Been looking at [your link](https://developers.binance.com/docs/api/apis#api-4-get-user-asset-balance) and it looks promising. But this appears to be part of their OAuth 2.0 API and I don't believe that this is open to all (see below).

![image](https://user-images.githubusercontent.com/6134409/152478827-5b8baaa3-da63-42b4-9871-dba2b46e3ad2.png)
