### ISSUE TITLE
R >= 3.5.0 enforced (not by DESCRIPTION file)

### ISSUE THREAD

**Issue by laresbernardo** [datawookie/binance#9]
Warning when installing the package. This happens because there are rda objects created with this limitation.
```
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
       ‘binance/data/coins.rda’ ‘binance/data/fiat.rda’
```
We can change DESCRIPTION file OR re-create these objects with version = 2 (i.e. `save(dfr, file = "data/fiat.rda", version = 2)`)

**Comment by laresbernardo** [comment]
Is it OK for you to give me permissions to create branches and push some code?
We can replace these objects with these new ones:
```
COINS <- binance::COINS
save(COINS, file = "data/coins.rda", version = 2)

FIAT <- binance::FIAT
save(FIAT, file = "data/fiat.rda", version = 2)
```

**Comment by datawookie** [comment]
Thanks, @laresbernardo. I have merged your changes. Also updated the `.R` files to set version to 2.
